USE agkv_db;

insert into user (firstname, lastname, email) values ('Maighdiln', 'Collard', 'mcollard0@census.gov');
insert into user (firstname, lastname, email) values ('Gray', 'Kempston', 'gkempston1@wikia.com');
insert into user (firstname, lastname, email) values ('Ezequiel', 'Pinsent', 'epinsent2@com.com');
insert into user (firstname, lastname, email) values ('Sascha', 'Jedraszczyk', 'sjedraszczyk3@google.com.br');
insert into user (firstname, lastname, email) values ('Conrad', 'Teal', 'cteal4@irs.gov');
insert into user (firstname, lastname, email) values ('Wilhelm', 'Kalvin', 'wkalvin5@devhub.com');
insert into user (firstname, lastname, email) values ('Ardisj', 'Illston', 'aillston6@rambler.ru');
insert into user (firstname, lastname, email) values ('Esta', 'Konerding', 'ekonerding7@seesaa.net');
insert into user (firstname, lastname, email) values ('Chastity', 'Berthot', 'cberthot8@eepurl.com');
insert into user (firstname, lastname, email) values ('Ethe', 'Cabbell', 'ecabbell9@pinterest.com');
insert into user (firstname, lastname, email) values ('Robinette', 'Thames', 'rthamesa@princeton.edu');
insert into user (firstname, lastname, email) values ('Elias', 'Timbridge', 'etimbridgeb@unesco.org');
insert into user (firstname, lastname, email) values ('Aveline', 'Sollam', 'asollamc@taobao.com');
insert into user (firstname, lastname, email) values ('Iolande', 'MacCallum', 'imaccallumd@hostgator.com');
insert into user (firstname, lastname, email) values ('Wilbert', 'Rattery', 'wratterye@dailymail.co.uk');
insert into user (firstname, lastname, email) values ('Rodrigo', 'Blemen', 'rblemenf@pinterest.com');
insert into user (firstname, lastname, email) values ('Guss', 'Tuddenham', 'gtuddenhamg@cbslocal.com');
insert into user (firstname, lastname, email) values ('Adham', 'Davley', 'adavleyh@dion.ne.jp');
insert into user (firstname, lastname, email) values ('Juan', 'Chitty', 'jchittyi@geocities.com');
insert into user (firstname, lastname, email) values ('Arne', 'Lamdin', 'alamdinj@hostgator.com');